
name: "CD Pipeline - Multi-Target Deploy"

on:
  workflow_dispatch:
    inputs:
      deploy_to:
        description: 'your choice '
        required: true
        default: 'runner'
        type: choice
        options:
          - runner
          - ec2

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}    
          password: ${{ secrets.DOCKERHUB_TOKEN }}   

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest

  deploy-to-runner:
    needs: build-and-push
    if: github.event.inputs.deploy_to == 'runner'
    runs-on: self-hosted
    steps:
      - name: Deploy on Local Runner
        run: |
          docker pull ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 80:80 ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest

  deploy-to-ec2:
    needs: build-and-push
    if: github.event.inputs.deploy_to == 'ec2'
    runs-on: ubuntu-latest  
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}    
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}  
          script: |
            sudo docker pull ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest
            sudo docker stop my-app || true
            sudo docker rm my-app || true
            sudo docker run -d --name my-app -p 80:80 ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest
